<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>3.2.5</version>
		<relativePath/>
	</parent>
	<groupId>com.paicbd.smsc</groupId>
	<artifactId>routing</artifactId>
	<version>3.2.0-SNAPSHOT</version>
	<name>routing</name>
	<description>Routing Module by PAiC</description>
	<licenses>
		<license>
			<name>GNU Affero General Public License</name>
			<url>http://www.gnu.org/licenses/agpl-3.0.html</url>
			<distribution>repo</distribution>
		</license>
	</licenses>
	<developers>
		<developer>
			<name>Enmanuel Calero</name>
			<email>enmanuel.calero@paicbd.com</email>
			<organization>PAiC BD</organization>
			<organizationUrl>https://paic-bd.com/</organizationUrl>
			<timezone>-6</timezone>
		</developer>
		<developer>
			<name>Obed Navarrete</name>
			<email>obed.navarrete@paicbd.com</email>
			<organization>PAiC BD</organization>
			<organizationUrl>https://paicbd.com</organizationUrl>
			<timezone>-6</timezone>
		</developer>
		<developer>
			<name>Melvin Mendoza</name>
			<email>melvin.mendoza@paicbd.com</email>
			<organization>PAiC BD</organization>
			<organizationUrl>https://paic-bd.com/</organizationUrl>
			<timezone>-6</timezone>
		</developer>
	</developers>
	<properties>
		<!-- Java version -->
		<java.version>21</java.version>

		<!-- Dependency versions -->
		<redis.clients.version>5.0.2</redis.clients.version>
		<jsmpp.version>3.1.5</jsmpp.version>
		<paic.licenser.version>2.0</paic.licenser.version>
		<smsc-utils.version>3.1.0-86</smsc-utils.version>
		<mockito.version>5.12.0</mockito.version>
		<junit.jupiter.version>5.10.3</junit.jupiter.version>
		<powermock.version>2.0.9</powermock.version>

		<!-- Plugin versions -->
		<codehaus.version>2.17.1</codehaus.version>
		<surfire.plugin.version>3.3.1</surfire.plugin.version>
		<sonar.scanner.version>4.0.0.4121</sonar.scanner.version>
		<jacoco.version>0.8.12</jacoco.version>
	</properties>
	<dependencies>
		<!-- Spring Boot dependencies -->
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-webflux</artifactId>
		</dependency>
		<dependency>
			<groupId>org.projectlombok</groupId>
			<artifactId>lombok</artifactId>
			<optional>true</optional>
		</dependency>
		<dependency>
			<groupId>redis.clients</groupId>
			<artifactId>jedis</artifactId>
			<version>${redis.clients.version}</version>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-websocket</artifactId>
		</dependency>
		<dependency>
			<groupId>com.fasterxml.jackson.core</groupId>
			<artifactId>jackson-databind</artifactId>
		</dependency>
		<dependency>
			<groupId>org.jsmpp</groupId>
			<artifactId>jsmpp</artifactId>
			<version>${jsmpp.version}</version>
		</dependency>
		<dependency>
			<groupId>com.paicbd</groupId>
			<artifactId>smsc-utils</artifactId>
			<version>${smsc-utils.version}</version>
		</dependency>
		<!-- Test dependencies -->
		<dependency>
			<groupId>org.mockito</groupId>
			<artifactId>mockito-core</artifactId>
			<version>${mockito.version}</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.mockito</groupId>
			<artifactId>mockito-junit-jupiter</artifactId>
			<version>${mockito.version}</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.junit.jupiter</groupId>
			<artifactId>junit-jupiter-api</artifactId>
			<version>${junit.jupiter.version}</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.junit.jupiter</groupId>
			<artifactId>junit-jupiter-engine</artifactId>
			<version>${junit.jupiter.version}</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.junit.jupiter</groupId>
			<artifactId>junit-jupiter-params</artifactId>
			<version>${junit.jupiter.version}</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.powermock</groupId>
			<artifactId>powermock-module-junit4</artifactId>
			<version>${powermock.version}</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.powermock</groupId>
			<artifactId>powermock-api-mockito2</artifactId>
			<version>${powermock.version}</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>io.projectreactor</groupId>
			<artifactId>reactor-test</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.awaitility</groupId>
			<artifactId>awaitility</artifactId>
			<scope>test</scope>
		</dependency>
	</dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
			</plugin>
			<plugin>
				<groupId>org.codehaus.mojo</groupId>
				<artifactId>versions-maven-plugin</artifactId>
				<version>${codehaus.version}</version>
				<executions>
					<execution>
						<goals>
							<goal>set</goal>
							<goal>commit</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-surefire-plugin</artifactId>
				<version>${surfire.plugin.version}</version>
				<configuration>
					<includes>
						<include>**/*Test.java</include>
					</includes>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.sonarsource.scanner.maven</groupId>
				<artifactId>sonar-maven-plugin</artifactId>
				<version>${sonar.scanner.version}</version>
			</plugin>
			<plugin>
				<groupId>org.jacoco</groupId>
				<artifactId>jacoco-maven-plugin</artifactId>
				<version>${jacoco.version}</version>
				<executions>
					<execution>
						<goals>
							<goal>prepare-agent</goal>
						</goals>
					</execution>
					<execution>
						<id>report</id>
						<phase>test</phase>
						<goals>
							<goal>report</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
		</plugins>
	</build>
</project>
